---
layout: post
title: "ES6 - Promise - 下篇"
data: 2017-09-25 9:27:00 +0800
categories: 学习笔记
tag: ES6
---
* content
{:toc}

> * 相关链接：
>   * [ES6 - Promise - 上篇](http://www.jmazm.com/2017/09/25/ES6-Promise/)

> * 以下内容全部源于： [http://es6.ruanyifeng.com/#docs/promise](http://es6.ruanyifeng.com/#docs/promise)


<!-- more -->

## 一、Promise.all()

### 1.1 用法介绍

> 1. `Promise.all`方法用于将多个 `Promise` 实例，包装成一个新的 `Promise` 实例。
> 2. `Promise.all`方法接受一个数组作为参数，例：`var p = Promise.all([p1, p2, p3]);`。
>    * `p1`、`p2`、`p3`都是 `Promise` 实例，如果不是，就会先调用下面讲到的`Promise.resolve`方法，将参数转为 `Promise` 实例，再进一步处理。
>    * （`Promise.all`方法的参数可以不是数组，但必须具有 `Iterator` 接口，且返回的每个成员都是 `Promise` 实例。）
> 3. `p`的状态由`p1`、`p2`、`p3`决定，分成两种情况。
>    1. 只有`p1`、`p2`、`p3`的状态都变成`fulfilled`，`p`的状态才会变成`fulfilled`，此时`p1`、`p2`、`p3`的返回值**组成一个数组**，传递给`p`的回调函数。
>    2. 只要`p1`、`p2`、`p3`之中有一个被`rejected`，`p`的状态就变成`rejected`，此时**第一个**被`reject`的实例的返回值，会传递给`p`的回调函数。

### 1.2 例1

> * `promises`是包含6个 `Promise` 实例的数组，只有这6个实例的状态都变成`fulfilled`，或者其中有一个变为`rejected`，才会调用`Promise.all`方法后面的回调函数。
> * **如果作为参数的 `Promise` 实例，自己定义了`catch`方法，那么它一旦被`rejected`，并不会触发`Promise.all()`的`catch`方法。**

```js
// 生成一个Promise对象的数组
var promises = [2, 3, 5, 7, 11, 13].map(function (id) {
  return getJSON('/post/' + id + ".json");
});

Promise.all(promises).then(function (posts) {
  // ...
}).catch(function(reason){
  // ...
});
```

### 1.3 例2

> * `p1`会`resolved`，`p2`首先会`rejected`，但是`p2`有自己的`catch`方法，该方法返回的是一个新的 `Promise` 实例，`p2`指向的实际上是这个实例。
> * 该实例执行完`catch`方法后，也会变成`resolved`，导致`Promise.all()`方法参数里面的两个实例都会`resolved`，因此会调用`then`方法指定的回调函数，而不会调用`catch`方法指定的回调函数。

```js
const p1 = new Promise((resolve, reject) => {
  resolve('hello');
})
.then(result => result)
.catch(e => e);

const p2 = new Promise((resolve, reject) => {
  throw new Error('报错了');
})
.then(result => result)
.catch(e => e);

Promise.all([p1, p2])
.then(result => console.log(result))
.catch(e => console.log(e));
// ["hello", Error: 报错了]
```

## 二、Promise.race()

> * `Promise.race`方法同样是将多个`Promise`实例，包装成一个新的`Promise`实例。
> * Promise.race方法的参数与Promise.all方法一样，如果不是 Promise 实例，就会先调用下面讲到的Promise.resolve方法，将参数转为 Promise 实例，再进一步处理。
> * 例子：`var p = Promise.race([p1, p2, p3]);`
>    * **只要`p1`、`p2`、`p3`之中有一个实例率先改变状态，`p`的状态就跟着改变。**
>    * **那个率先改变的 `Promise` 实例的返回值，就传递给`p`的回调函数。**

---

> * 例：如果指定时间内没有获得结果，就将`Promise`的状态变为`reject`，否则变为`resolve`。
> * 如果5秒之内`fetch`方法无法返回结果，变量`p`的状态就会变为`rejected`，从而触发`catch`方法指定的回调函数。

```js
const p = Promise.race([
  fetch('/resource-that-may-take-a-while'),
  new Promise(function (resolve, reject) {
    setTimeout(() => reject(new Error('request timeout')), 5000)
  })
]);
p.then(response => console.log(response));
p.catch(error => console.log(error));
```

## 三、Promise.resolve()

### 3.1 用法

> * `Promise.resolve()`：将现有对象转化为`Promise`对象。

```js
Promise.resolve('foo')
// 等价于
new Promise(resolve => resolve('foo'))
```

> * `Promise.resolve`方法的参数分成四种情况。

### 3.2 .参数是一个Promise实例 或 thenable对象

> * 1.参数是一个Promise实例
>    * 如果参数是`Promise`实例，那么`Promise.resolve`将不做任何修改、原封不动地返回这个实例。

> * 2.参数是一个`thenable`对象
>    * `thenable`对象指的是具有`then`方法的对象。
>    * `Promise.resolve`方法会将这个对象转为`Promise`对象，然后就立即执行`thenable`对象的`then`方法。

> * 例：
> * `thenable`对象的`then`方法执行后，对象`p1`的状态就变为`resolved`，从而立即执行最后那个`then`方法指定的回调函数，输出42。

```js
let thenable = {
  then: function(resolve, reject) {
    resolve(42);
  }
};

let p1 = Promise.resolve(thenable);
p1.then(function(value) {
  console.log(value);  // 42
});
```

### 3.3 .参数不是具有then方法的对象，或根本就不是对象

> * 如果参数是一个原始值，或者是一个不具有`then`方法的对象，则`Promise.resolve`方法返回一个新的`Promise`对象，**状态为`resolved`**。

> * 例：
> * 生成一个新的`Promise`对象的实例`p`。
> * 由于字符串`Hello`**不属于异步操作**（**判断方法是字符串对象不具有`then`方法**），返回`Promise`实例的状态从一生成就是`resolved`，所以回调函数会立即执行。
> * `Promise.resolve`方法的参数，会同时传给回调函数。

```js
var p = Promise.resolve('Hello');

p.then(function (s){
  console.log(s)
});
// Hello
```

### 3.3 不带任何参数

>  * `Promise.resolve`方法允许调用时不带参数，直接返回一个`resolved`状态的`Promise`对象。
>  * **立即`resolve`的`Promise`对象，是在本轮“事件循环”（`event loop`）的结束时，而不是在下一轮“事件循环”的开始时。**

> 例：
> * `setTimeout(fn, 0)`在下一轮“事件循环”开始时执行，`Promise.resolve()`在本轮“事件循环”结束时执行，`console.log('one')`则是立即执行，因此最先输出。

```js
setTimeout(function () {
  console.log('three');
}, 0);

Promise.resolve().then(function () {
  console.log('two');
});

console.log('one');

// one
// two
// three
```

## 四、Promise.reject()

* `Promise.reject(reason)`方法也会返回一个新的 `Promise` 实例，该实例的状态为`rejected`。
    * `Promise.reject()`方法的参数，会原封不动地作为`reject`的理由，变成后续方法的参数。这一点与`Promise.resolve`方法不一致。

> 例：
> * `Promise.reject`方法的参数是一个`thenable`对象，执行以后，后面`catch`方法的参数不是`reject`抛出的“出错了”这个字符串，而是`thenable`对象。

```js
const thenable = {
  then(resolve, reject) {
    reject('出错了');
  }
};

Promise.reject(thenable)
.catch(e => {
  console.log(e === thenable)
})
// true
```

## 五、两个有用的附加方法

### 5.1 done()

> * 1.done()
>    * `Promise`对象的回调链，不管以`then`方法或`catch`方法结尾，要是最后一个方法抛出错误，都有可能无法捕捉到
>    * （因为`Promise`内部的错误不会冒泡到全局）。
>    * 因此，我们可以提供一个`done`方法，总是处于回调链的尾端，保证抛出任何可能出现的错误。

```js
asyncFunc()
  .then(f1)
  .catch(r1)
  .then(f2)
  .done();
```

> * 实现代码：
> * `done`方法的使用，可以像`then`方法那样用，提供`fulfilled`和`rejected`状态的回调函数，也可以不提供任何参数。
> * 但不管怎样，**`done`都会捕捉到任何可能出现的错误，并向全局抛出**。

```js
Promise.prototype.done = function (onFulfilled, onRejected) {
  this.then(onFulfilled, onRejected)
    .catch(function (reason) {
      // 抛出一个全局错误
      setTimeout(() => { throw reason }, 0);
    });
};
```

### 5.2 finally()

> * `finally`方法用于指定不管`Promise`对象最后状态如何，都会执行的操作。
> * 它与`done`方法的最大区别，它接受一个普通的回调函数作为参数，**该函数不管怎样都必须执行**。

> * 实现代码
> * 不管前面的`Promise`是`fulfilled`还是`rejected`，都会执行回调函数`callback`。

```js
Promise.prototype.finally = function (callback) {
  let P = this.constructor;
  return this.then(
    value  => P.resolve(callback()).then(() => value),
    reason => P.resolve(callback()).then(() => { throw reason })
  );
};
```

## 六、应用

### 6.1 加载图片

```js
const preloadImage = function (path) {
  return new Promise(function (resolve, reject) {
    var image = new Image();
    image.onload  = resolve;
    image.onerror = reject;
    image.src = path;
  });
};
```

### 6.2 Generator函数与Promise的结合

* 使用`Generator`函数管理流程，遇到异步操作的时候，通常返回一个`Promise`对象。

```js
function getFoo () {
  return new Promise(function (resolve, reject){
    resolve('foo');
  });
}

var g = function* () {
  try {
    var foo = yield getFoo();
    console.log(foo);
  } catch (e) {
    console.log(e);
  }
};

function run (generator) {
  var it = generator();

  function go(result) {
    if (result.done) return result.value;

    return result.value.then(function (value) {
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(error));
    });
  }

  go(it.next());
}

run(g);
```

* 上面代码的Generator函数g之中，有一个异步操作getFoo，它返回的就是一个Promise对象。函数run用来处理这个Promise对象，并调用下一个next方法。

## 七、 Promise.try()

* 实际开发中，经常遇到一种情况：不知道或者不想区分，函数f是同步函数还是异步操作，但是想用 `Promise` 来处理它。
    * 因为这样就可以不管f是否包含异步操作，都用then方法指定下一步流程，用catch方法处理f抛出的错误。
    * 一般就会采用下面的写法。【**有一个缺点，就是如果f是同步函数，那么它会在本轮事件循环的末尾执行。**】

```js
Promise.resolve().then(f)
```

> 例1：
>   * 函数`f`是同步的，但是用 `Promise` 包装了以后，就变成异步执行了。

```js
const f = () => console.log('now');
Promise.resolve().then(f);
console.log('next');
// next
// now
```

* **让同步函数同步执行，异步函数异步执行，并且让它们具有统一的 `API`，有两种写法：**

* 1.用async函数

> 例：
> * 第二行是一个立即执行的匿名函数，会立即执行里面的`async`函数。
> * 因此如果`f`是同步的，就会得到同步的结果；如果`f`是异步的，就可以用`then`指定下一步。
